<?php

/**
 * BaseClients
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $what_next
 * @property string $description
 * @property string $price
 * @property timestamp $start_dev_date
 * @property timestamp $stop_dev_date
 * @property string $ip_address
 * 
 * @method string    getName()           Returns the current record's "name" value
 * @method string    getPhone()          Returns the current record's "phone" value
 * @method string    getEmail()          Returns the current record's "email" value
 * @method string    getWhatNext()       Returns the current record's "what_next" value
 * @method string    getDescription()    Returns the current record's "description" value
 * @method string    getPrice()          Returns the current record's "price" value
 * @method timestamp getStartDevDate()   Returns the current record's "start_dev_date" value
 * @method timestamp getStopDevDate()    Returns the current record's "stop_dev_date" value
 * @method string    getIpAddress()      Returns the current record's "ip_address" value
 * @method Clients   setName()           Sets the current record's "name" value
 * @method Clients   setPhone()          Sets the current record's "phone" value
 * @method Clients   setEmail()          Sets the current record's "email" value
 * @method Clients   setWhatNext()       Sets the current record's "what_next" value
 * @method Clients   setDescription()    Sets the current record's "description" value
 * @method Clients   setPrice()          Sets the current record's "price" value
 * @method Clients   setStartDevDate()   Sets the current record's "start_dev_date" value
 * @method Clients   setStopDevDate()    Sets the current record's "stop_dev_date" value
 * @method Clients   setIpAddress()      Sets the current record's "ip_address" value
 * 
 * @package    site-develope
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClients extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clients');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Имя',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Телефон',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'E-mail',
             'length' => 255,
             ));
        $this->hasColumn('what_next', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'comment' => 'На чем остановились с клиентом',
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'comment' => 'Описание проекта',
             'length' => '',
             ));
        $this->hasColumn('price', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Цена проекта',
             'length' => 255,
             ));
        $this->hasColumn('start_dev_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             'comment' => 'Дата начала работы',
             ));
        $this->hasColumn('stop_dev_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             'comment' => 'Дата окончания работы',
             ));
        $this->hasColumn('ip_address', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'IP адрес',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}