# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Site-develope.ru
    description:  Site-develope.ru
    keywords:     Site, develope
    language:     ru
    #robots:       index, follow

  stylesheets:    [admin_main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
