<?php

/**
 * BenefitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BenefitsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BenefitsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Benefits');
    }
}