<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('clients', 'start_dev_date', 'timestamp', '25', array(
             'notnull' => '',
             'comment' => 'Дата начала работы',
             ));
        $this->addColumn('clients', 'stop_dev_date', 'timestamp', '25', array(
             'notnull' => '',
             'comment' => 'Дата окончания работы',
             ));
    }

    public function down()
    {
        $this->removeColumn('clients', 'start_dev_date');
        $this->removeColumn('clients', 'stop_dev_date');
    }
}