<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('clients', 'ip_address', 'string', '100', array(
             'notnull' => '',
             'comment' => 'IP адрес',
             ));
    }

    public function down()
    {
        $this->removeColumn('clients', 'ip_address');
    }
}