generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Benefits
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          benefits
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id:       { label: "ID" }
        title:    { label: "Название преимущества" }
        text:     { label: "Текст преимущества" }
        image:    { label: "Картинка" }
      list:
        title: 'Наши преимущества'
        display:  [id, =title, text, _image]
      filter:
        display:  [title, text]
      form:
        class: BackendBenefitsForm
        display:  [title, text, image]
      edit:
        title: 'Редактирование преимущества'
      new:
        title: 'Новое преимущество'
