generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Services
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          services
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id:       { label: "ID" }
        title:    { label: "Название услуги" }
        text:     { label: "Текст услуги" }
        image:    { label: "Картинка" }
      list:
        title: 'Наши услуги'
        display:  [id, =title, text, _image]
      filter:
        display:  [title, text]
      form:
        class: BackendServicesForm
        display:  [title, text, image]
      edit:
        title: 'Редиктирование услуги'
      new:
        title: 'Создание услуги'
